repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1 # https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        args: ["--unsafe"]
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0 # https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
